"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { Printer } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Page, PageHeader, Section } from "@/components/app/page-header";
import { StatusBadge, Mono } from "@/components/app/status";
import { CustomerLink, KeyValue, LinesTable, Totals, whCode } from "@/components/app/entity";
import { FbrPanel } from "@/components/app/fbr";
import { RecordPaymentDialog } from "@/components/app/record-payment";
import { getDB, idx, invoiceStatusLabel } from "@/lib/data/queries";
import { dateLong, dateShort, money } from "@/lib/format";
import { useOverlay } from "@/lib/overlay";
import { useERP } from "@/lib/store";
import { can } from "@/lib/rbac";
import { diffDays } from "@/lib/data/dates";

export default function InvoiceDetail() {
  const { id } = useParams<{ id: string }>();
  const ov = useOverlay();
  const role = useERP((s) => s.role);
  const db = getDB();
  const base = idx().inv.get(id);
  if (!base) return <Page><p className="text-sm text-muted-foreground">Invoice not found.</p></Page>;
  const inv = ov.invoice(base);
  const c = idx().cus.get(inv.customerId)!;
  const status = invoiceStatusLabel(inv, db.today);
  const pays = [...ov.payments, ...db.payments].filter((p) => p.allocations.some((a) => a.invoiceId === inv.id));
  const je = db.journal.filter((j) => j.source === `Invoice ${inv.number}`);
  const cn = db.creditNotes.filter((x) => x.invoiceId === inv.id);
  const taxCats = new Map<string, number>();
  for (const l of inv.lines) { const p = idx().prod.get(l.productId)!; taxCats.set(p.taxCategory, (taxCats.get(p.taxCategory) ?? 0) + l.salesTax); }
  const overdueDays = diffDays(db.today, inv.dueDate);
  return (
    <>
      <PageHeader back={{ href: "/sales/invoices", label: "Invoices" }} title={<span className="flex items-center gap-3"><Mono className="text-xl">{inv.number}</Mono><StatusBadge status={status} /></span>}
        description={<span><CustomerLink id={inv.customerId} /> · issued {dateLong(inv.date)} · due {dateLong(inv.dueDate)}{status === "overdue" ? ` · ${overdueDays} days overdue` : ""}</span>}
        actions={<><Button variant="outline" size="sm" onClick={() => window.print()}><Printer />Print / PDF</Button>{can(role, "payment.record") && inv.total - inv.paid > 0.5 && <RecordPaymentDialog customerId={inv.customerId} defaultAmount={inv.total - inv.paid} trigger={<Button size="sm">Record payment</Button>} />}</>} />
      <Page>
        <div className="grid gap-4 lg:grid-cols-3">
          <div className="space-y-4 lg:col-span-2">
            <Section title="Lines" flush>
              <LinesTable lines={inv.lines} />
              <Totals rows={[
                { label: "Gross sales", value: inv.subtotal, muted: true }, { label: "Discounts & schemes", value: -inv.discount, muted: true }, { label: "Sales tax", value: inv.salesTax, muted: true },
                { label: "Further tax (unregistered buyer)", value: inv.furtherTax, muted: true }, { label: "Advance tax u/s 236H", value: inv.wht236h, muted: true }, { label: "Invoice total", value: inv.total, strong: true },
                { label: "Paid", value: inv.paid, muted: true }, { label: "Balance due", value: inv.total - inv.paid, strong: true },
              ]} />
            </Section>
            <Section title="Accounting" description="Journal entries generated by this document" flush>
              {je.map((j) => (
                <div key={j.id} className="border-b last:border-0">
                  <div className="flex items-center justify-between px-4 py-2 text-xs text-muted-foreground"><Link href="/finance/journal" className="font-mono hover:text-foreground">{j.number}</Link><span>{dateShort(j.date)} · {j.memo}</span></div>
                  <table className="w-full text-[13px]"><tbody>{j.lines.map((l, i) => (
                    <tr key={i} className="border-t"><td className="px-4 py-1.5"><Mono className="mr-2 text-muted-foreground">{l.account}</Mono>{idx().acct.get(l.account)?.name}</td><td className="w-32 px-4 py-1.5 text-right tabular">{l.debit ? money(l.debit) : ""}</td><td className="w-32 px-4 py-1.5 text-right tabular">{l.credit ? money(l.credit) : ""}</td></tr>
                  ))}</tbody></table>
                </div>
              ))}
            </Section>
          </div>
          <div className="space-y-4">
            <Section title="FBR e-invoice"><FbrPanel inv={inv} /></Section>
            <Section title="Details"><KeyValue cols={1} items={[["Customer", <CustomerLink key="c" id={c.id} />], ["Buyer tax identity", c.registered ? `NTN ${c.ntn} · STRN ${c.strn}` : `Unregistered · CNIC ${c.cnic}`], ["ATL status", c.atl ? "Active taxpayer" : "Not on ATL"], ["Dispatched from", whCode(inv.warehouseId)], ["Sales order", <Link key="o" className="font-mono text-xs hover:text-primary" href={`/sales/orders/${inv.orderId}`}>{idx().db.orders.find((o) => o.id === inv.orderId)?.number}</Link>], ["Payment terms", `${c.termsDays} days`], ["Tax basis", [...taxCats.keys()].map((k) => (k === "third_schedule" ? "Retail price (3rd Sch.)" : k === "exempt" ? "Exempt" : "Standard 18%")).join(" · ")]]} /></Section>
            <Section title="Payments" flush>
              {pays.length === 0 ? <p className="px-4 py-5 text-center text-xs text-muted-foreground">No payments recorded.</p> : (
                <ul className="divide-y">{pays.map((p) => (<li key={p.id} className="flex items-center justify-between gap-3 px-4 py-2.5 text-[13px]"><div><Mono>{p.number}</Mono><div className="text-xs text-muted-foreground">{dateShort(p.date)} · {p.method.replace("_", " ")}</div></div><div className="text-right"><div className="tabular">{money(p.allocations.find((a) => a.invoiceId === inv.id)!.amount)}</div><StatusBadge status={p.status} /></div></li>))}</ul>
              )}
              {cn.map((x) => <div key={x.id} className="border-t px-4 py-2.5 text-[13px]"><Mono>{x.number}</Mono> credit note · {money(x.total)} · {x.reason.replace("_", " ")}</div>)}
            </Section>
          </div>
        </div>
      </Page>
    </>
  );
}
