// Product knowledge for the assistant: what each screen is for and how to do common tasks.
// Retrieved by the how_to tool (and summarised in the system prompt) so the assistant can teach, not just answer.
import type { Action } from "../rbac";
export interface GuideEntry { id: string; title: string; keywords: string; path: string; steps: string[]; notes?: string; needs?: Action }

export const GUIDE: GuideEntry[] = [
  { id: "create-order", needs: "order.create", title: "Create a sales order", keywords: "sales order create new order book customer reserve stock confirm credit", path: "/sales/orders/new", steps: ["Open Sales → New order.", "Pick the customer; their limit, outstanding and risk show beside it.", "Add products (cartons). Prices come from the customer's channel price list; schemes like 10+1 free goods apply automatically.", "Check the right-hand checklist: pricing, taxes, stock, credit.", "Confirm order reserves stock. If credit is blocked, save a draft and use Request credit override on the order page."], notes: "Only Owner, Admin, Sales Manager and Order Booker can create orders; for other roles the New order button is greyed out (switch persona at the bottom of the sidebar). Reps only see their own customers. Over-limit orders need a Sales Manager approval." },
  { id: "record-payment", needs: "payment.record", title: "Record a customer payment", keywords: "payment receipt record cash cheque bank transfer allocate invoice collect pdc bounce", path: "/sales/payments", steps: ["Open Sales → Payments → Record payment (or use it from a customer or invoice).", "Choose the customer, amount and method. Cheques ask for a cheque number.", "It is allocated to the oldest open invoices first and posts Dr Bank / Cr Trade Debtors."], notes: "Cheque register and bounced cheques are views on the Payments tab." },
  { id: "approve", title: "Approve or reject requests", keywords: "approve approval inbox reject purchase order expense credit limit variance", path: "/approvals", steps: ["Open Approvals (top bar counter).", "Select an item to see its detail and evidence.", "Add a comment and Approve or Reject. The action runs through the normal command and is written to the audit log."], notes: "POs above Rs 1,000,000 need the Owner. You can't approve your own request." },
  { id: "replenish", needs: "po.create", title: "Replenish stock / create a purchase order from a recommendation", keywords: "reorder replenish purchase order stockout low stock recommendation forecast buy", path: "/inventory/replenishment", steps: ["Open Inventory → Replenishment.", "Each card shows availability, 30-day forecast, lead time and why. Expand Why? for reasoning.", "Adjust the quantity (whole cartons) and click Create purchase order.", "Approve the PO in Approvals if it is above your limit; incoming stock and the cash forecast update."] },
  { id: "three-way-match", needs: "approve.finance", title: "Resolve a supplier bill variance or duplicate", keywords: "supplier bill invoice variance duplicate three-way match price exception ppv credit note", path: "/purchasing/bills", steps: ["Open Purchasing → Supplier bills and click a bill marked Exception.", "Compare PO ↔ goods receipt ↔ bill; exceptions are listed with amounts.", "Approve with variance (posts purchase price variance), request a credit note, or reject (for duplicates).", "Add a reason: it is stored in the audit log."] },
  { id: "extract-bill", title: "Extract a bill from a document", keywords: "extract upload document ocr invoice pdf receipt ai read", path: "/purchasing/bills", steps: ["On Supplier bills click Extract from document.", "Pick a sample invoice; the AI reads fields, matches the supplier and PO and validates arithmetic.", "Open the draft bill for review; nothing posts until you approve."] },
  { id: "reports", title: "Run a report for a date range", keywords: "report revenue sales date range from to export filter drill down customer product region rep margin", path: "/reports", steps: ["Open Reports and choose a report (sales by customer/product/region/rep, margin, valuation…).", "Choose the period preset, or ask the assistant for exact dates.", "Click a row to drill into the customer, product or supplier; Export downloads CSV."] },
  { id: "statements", title: "Profit & Loss, Balance Sheet, Cash Flow, Trial Balance", keywords: "profit loss p&l balance sheet cash flow trial balance statements ledger account drill", path: "/finance/statements", steps: ["Open Finance → Statements and pick the period (FY to date, last FY, last 3 months).", "Switch tabs for P&L, Balance Sheet, Cash Flow or Trial Balance.", "Click any account to open its general-ledger lines and the source document."] },
  { id: "cashflow", title: "Cash-flow forecast", keywords: "cash flow forecast projection runway minimum cash weeks collections", path: "/finance/cashflow", steps: ["Open Finance → Cash-flow forecast.", "The chart shows 13 weeks against the minimum cash line; the table shows collections, supplier payments, payroll and open POs per week.", "Assumptions are listed below; approving a PO updates the projection."] },
  { id: "journal", title: "Post a manual journal entry", keywords: "journal manual entry post debit credit period closed reversal ledger", path: "/finance/journal", steps: ["Open Finance → Journal & ledger → New journal entry.", "Enter date, memo and balanced debit/credit lines.", "Closed periods and control accounts (debtors, creditors, stock) are rejected with an explanation; entries above Rs 500,000 need a second approver."], notes: "Posted entries are immutable; correct with a reversal." },
  { id: "reconcile", title: "Reconcile the bank statement", keywords: "bank reconciliation reconcile match statement suggestion unmatched", path: "/finance/reconciliation", steps: ["Open Finance → Bank reconciliation.", "Confident matches are automatic; AI-assisted suggestions show the method and confidence.", "Confirm or reject each suggestion; unmatched lines need investigation."] },
  { id: "customers-risk", title: "Find overdue or risky customers", keywords: "overdue risky customers risk credit limit outstanding balance aging collections follow up", path: "/customers?overdue=1", steps: ["Open Customers; use the Overdue / High risk / Over credit limit views or the filters.", "Open a customer to see aging, payment trend and the risk factors.", "Use Contact → Draft follow-up with AI, or ask the assistant to draft messages."] },
  { id: "stock-count", needs: "warehouse.ops", title: "Count stock / transfer between warehouses", keywords: "stock count cycle count transfer warehouse variance discrepancy shortage", path: "/warehouses", steps: ["Open Warehouses and pick a warehouse.", "Start cycle count for a blind count (expected quantities hidden) or Transfer to move stock.", "Variances over Rs 50,000 need Finance approval."] },
  { id: "tax-fbr", title: "Tax rules and FBR e-invoicing", keywords: "tax fbr sales tax further tax 236g 236h irn qr ntn strn atl digital invoicing", path: "/finance/tax", steps: ["Open Finance → Tax & FBR to see output/input tax, further tax and the FBR submission log.", "Every invoice carries an IRN and QR; the demo marks them Simulated.", "Third Schedule goods are taxed on retail price; unregistered or non-ATL buyers add further tax."], notes: "Rates are demo configuration; verify with a tax advisor." },
  { id: "expenses", title: "Submit and approve expenses", keywords: "expense claim receipt submit reimbursement policy manager finance", path: "/expenses", steps: ["Open Expenses → Submit expense and capture a receipt.", "Amount, merchant and category are read; duplicates and policy are checked.", "It goes Employee → Manager → Finance."] },
  { id: "roles", title: "Switch role to try permissions", keywords: "role persona permission access switch user rbac owner finance rep warehouse", path: "/settings/roles", steps: ["Click your avatar (top right) and pick a demo persona.", "Navigation and actions change to match that role (e.g. reps see only their customers).", "Settings → Users & roles shows the full matrix."] },
  { id: "shortcuts", title: "Keyboard shortcuts", keywords: "keyboard shortcut hotkey command palette search", path: "/overview", steps: ["⌘/Ctrl+K opens search and commands (try “overdue customers in Karachi over 1 million”).", "⌘/Ctrl+/ opens this assistant.", "g then o/s/c/i/p/f/a jumps to Overview/Sales/Customers/Inventory/Purchasing/Finance/AI.", "[ collapses the sidebar; j/k and Enter move through table rows."] },
  { id: "audit", title: "See who did what", keywords: "audit log history who changed trail ai proposal source", path: "/settings/audit", steps: ["Open Settings → Audit log.", "Filter by source (person, AI proposal, system, workflow).", "AI-confirmed actions show the proposal reference and who confirmed them."] },
];

export const APP_MAP = `Overview (KPIs, AI brief, approvals) · Sales: Orders, Quotations, Invoices, Payments, Returns, Leads · Customers (+ detail) · Inventory: Products, Replenishment, Stock position, Expiry · Warehouses · Purchasing: Purchase orders, Goods receipts, Supplier bills, Payments · Suppliers · Finance: Statements, Cash-flow forecast, Receivables, Payables, Journal & ledger, Bank reconciliation, Tax & FBR · Expenses · Employees: Directory, Leave, Payroll · Reports · AI Command Center · Automations · Integrations · Settings: Organization, Users & roles, Audit log, AI, System health · Approvals (top bar).`;

export function findGuide(topic: string, limit = 2): GuideEntry[] {
  const words = topic.toLowerCase().split(/[^a-z0-9&]+/).filter((w) => w.length > 2);
  return GUIDE.map((g) => ({ g, score: words.reduce((s, w) => s + (g.keywords.includes(w) ? 2 : 0) + (g.title.toLowerCase().includes(w) ? 3 : 0), 0) })).filter((x) => x.score > 0).sort((a, b) => b.score - a.score).slice(0, limit).map((x) => x.g);
}
